// Code generated by volt v0.0.0-dev.13659c3 — DO NOT EDIT.
//
// Regenerate:  volt gen
// To change:   edit .volt.yml, or the template in volt itself — edits here are lost.
// volt:hash 00c556fa7b19
package main

import (
	"github.com/khanakia/voltkit/skillcmd"
	"github.com/spf13/cobra"
)

// newSkillsCommand serves this project's published skills — content fetched
// once per binary version into the OS cache and served from there, always
// matching this binary. See github.com/khanakia/voltkit/skillcmd.
func newSkillsCommand() *cobra.Command {
	return skillcmd.New(skillcmd.Options{
		Binary:  "browserctrl",
		Repo:    "khanakia/browserctrl",
		Version: version, // the project's stamped version variable
		Tag:     "browserctrl/" + version,
		// The detected forge's download shape, fixed at gen time — the
		// binary never guesses its host.
		AssetURLTemplate: "https://github.com/khanakia/browserctrl/releases/download/{tag}/{asset}",
	})
}
